os: linux
dist: xenial
branches:
  only:
    - master
# Update list of available packages and install cartopy C++ dependencies
before_install:
  - sudo apt-get update --quiet
  - sudo apt-get install libgeos-dev libproj-dev
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
language: python
python:
  - "3.8"
install:
  - $HOME/.poetry/bin/poetry install -v
script:
  - $HOME/.poetry/bin/poetry run pytest --verbose --cov=scripts/ tests/
after_success:
  - codecov
notifications:
    email:
        on_success: change
        on_failure: always
