sudo: required  # see https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
dist: trusty
branches:
  only:
    - master
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install proj-bin -y
language: python
python:
  - "3.6"
cache:
  pip: true
install:
  - pip install pipenv
  - pip install codecov
script: pipenv install --dev && pipenv run tests
after_success:
  - codecov
notifications:
    email:
        on_success: change
        on_failure: always
